### ISSUE TITLE
テキスト音声合成ライブラリの作成

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_project#1]
テキスト音声合成ができる薄いライブラリを作る計画です。
今エンジンとコアに機能が分離しているので、これらをうまいことまとめる必要があります。

**Comment by Hiroshiba** [comment]
最初に要議論で、議論はこちらで行われています

- https://github.com/VOICEVOX/voicevox_core/issues/43

**Comment by Hiroshiba** [comment]
このプロジェクトの内容を「C++ TTSライブラリ化」に軌道修正し、本格的に稼働したいです。

C++ TTSライブラリができると嬉しいことはこんな感じです。

* 別言語に組み込みやすくなる
  * ので、例えば動画作成ツールで気軽に連携してもらえる
  * discordのbot作成などの趣味プログラミングで採用されやすくなる
  * スマホ移植やwebフロント移植などもしやすくなる

どこまでできるようにすべきかですが、まず初手は単純なTTS（文字→音声）ができるライブラリにするのが良いかなと思います。

- [ ] 単純なTTS（文字→音声）の実装

その次が迷っているのですが、AquesTalk記法を使用可能にするか、中間表現（エンジンのQuery）を修正できるレベルを目指したいです。

- [ ] AquesTalk記法の実装
- [ ] 中間表現（エンジンのQuery）のやりとりを実装

モーフィング機能・辞書編集機能などは一旦保留にして上記２つを注力すれば良いのかなと思っています。

**Comment by qwerty2501** [comment]
どのように配布するつもりでいますか？ DLLでしょうか？
またAPIをどうする想定でいますか？(素朴な C APIを定義しFFIされる想定か、そうではないか)
> 別言語に組み込みやすくなる

これは各言語ごとにラッパーライブラリができて初めて成立すると思うので、C++製ライブラリ+ラッパーライブラリの作成を行う必要がありそうです。

**Comment by Hiroshiba** [comment]
配布は今のVOICEVOX COREと同じで、動的ライブラリの形式を考えています。
APIも今のコアと同じでexternすれば良いのかなと思っています。（こちらは単純にそれ以外の方法に関する知識がなく。。）

言語ごとにラッパーライブラリが作れると嬉しいですね！！
あとあとエンジンでも活用できると嬉しいので、特にpythonラッパーは作るモチベーションがありそうです。
とりあえずこのissueはC++ライブラリの作成を目指したいです。
１つめのマイルストーンの`単純なTTS（文字→音声）の実装`ができ次第、ラッパーを作り始めても良いかもですね！

**Comment by qwerty2501** [comment]
そういえば以前コメントした[これ](https://github.com/VOICEVOX/voicevox_core/issues/43#issuecomment-997166989)を検討しても良いかもしれませんがどうしましょうかね。
この場合だとC++のclassを元にして作る感じになるようなので作り方が変わってしまいますが。
とりあえず何も使わずにC APIでの公開にしておきますか？

**Comment by Hiroshiba** [comment]
SWIGも面白そうです。本格的に多言語展開する際にぜひ検討したいですね！
初手はとりあえずC APIとして公開を目指しましょう。同時並行で調査しておくと良いかも？

struct情報に関しては･･･あ、今のエンジンみたくjsonでやり取りするというのはどうでしょう。
エラーメッセージのとこみたく、ライブラリ側でjson文字列のメモリを確保してアドレスを返し、その解放はライブラリ側が担当するとか･･･
いやこうすると並列で取得したときにおかしくなりますね･･･うーん。

**Comment by qwerty2501** [comment]
SWIGについて少し調べましたが、Swift/Objective-Cの出力がサポートされてないようなのでスマホターゲットを考慮するとiOSをどうするかSWIGを使うにしても考えなければならなそうです。

> エラーメッセージのとこみたく、ライブラリ側でjson文字列のメモリを確保してアドレスを返し、その解放はライブラリ側が担当するとか･･･
いやこうすると並列で取得したときにおかしくなりますね･･･うーん、できればメモリ確保の手間は避けられるようにしたいですが、なにか良い方法ないですかね･･･

coreのエラーメッセージのやつですよね。あれは絶対にやめたほうが良いと思います。
structのフィールドを絶対に変えないという確信がある場合はstructを公開してもよいかもですが、その場合でも文字列用に確保したheapメモリの管理をしなければならず、どのみち手間になります。手間というよりは危険というべきかもですが。

C APIでDLLを扱う場合は、ライブラリの構造体用に確保したメモリの管理操作はユーザー側で行うのが一般的ではあるので、これを避けたければwrapperを提供し、その内部でメモリの管理を行うアプローチが良いのではないでしょうか？

SWIGだと定義したclass/structを指定するとそのコードを各言語用に出力できるようなので、そのあたりの処理コードを自動で出力してくれそうです。

**Comment by Hiroshiba** [comment]
SWIG、面白そうなのですが、ライセンスがGPLなので厳しそうでした。。。

一旦SWIGから離れて、最適解を探せればと思いました。

いま問題なのは、「可変長のメモリサイズが必要なパラメータを返すのはどうすればいいか」だという認識です。
C APIで実装するなら、よくある方法だと

1. メモリサイズを返す
2. mallocしてもらう
3. memcpyする

でしょうか。
ユーザー側もこちらの実装側もちょっと手間ですが、この方法以外思いつかないのであればこの方法しかないのかなと感じました。。

**Comment by y-chan** [comment]
C APIに関して、以前AquesTalk10のNode.jsラッパーを書いたことがあり、AquesTalkがwavを生成する際はメモリアドレスとメモリサイズを返す、を行っていました。
また、AquesTalkに関して言えばメモリの解放もAquesTalk側が担っていました(`AquesTalk_FreeWave`関数が存在します)
なので、アドレスとサイズを元にmalloc/memcpyし、FreeWaveを実行していたと思います。
前に倣えになりはしますが、私もHiroshibaさんが挙げた手法が最も扱いやすい気がします。

**Comment by qwerty2501** [comment]
@Hiroshiba ライセンスGPLってSWIG自体ですよね？SWIGはライブラリではなくコード生成なので大丈夫な気がします(要調査)
ただ一旦C APIでやるという点については私も賛成です。

ちょっと上手く伝わってなかったのですが、メモリ確保/開放はライブラリ側で関数用意するイメージですね。
ただCなので、開放はその関数を明示的にユーザーが呼び出してやるイメージです。
ユーザー側がメモリサイズを指定したり、標準ライブラリのmalloc/freeを呼び出す実装だと実装ミスが多くなりそうなので避けたほうが良さそうです。

この構造体実装を隠すテクニックは [Opaqueポインタ](https://minus9d.hatenablog.com/entry/2016/01/13/213751) とよばれてるので参考にしていただければ

**Comment by Hiroshiba** [comment]
では一旦C APIで･･･！
なるほどです、ライブラリ側でmalloc/freeを呼べば簡単という発想がなかったのでちょっと勘違いしてしまいました。
y-chanさんも仰ってる通り、ライブラリ側でmalloc/freeするのが良いと思います！

構造体の件ですが、そもそもデータの型がコード（`header.h`）に、データの内容がバイナリにある状態を避けたいかもです。
仰るとおりバージョンがずれるリスクがあります。
ので、データの形と、データの中身どちらも返す機構にしたいです。
一番手っ取り早いのはエンジンみたいにjson stringを返す方法かなと思っていますが、どうでしょう。

**Comment by qwerty2501** [comment]
あまり一般的なアプローチではないのでユーザーからは違和感は持たれそうです。open jtalkのlabel formatが文字列で返されましたが、あれと似たような違和感があるかと

> そもそもデータの型がコード（header.h）データの内容がバイナリにある状態を避けたいかもです

Opaqueポインタを使えばこれは達成できると思いますが、json文字列にしたいモチベーションは何でしょうか？

> データの形と、データの中身どちらも返す機構にしたいです

データの形とは何でしょう？

**Comment by Hiroshiba** [comment]
そもそもstructは避けたいモチベーションがある感じです。

PythonにあるCythonでCラッパーを書いて思ったのですが、structなどのCの独自言語仕様があるとコンパイルが面倒なんですよね･･･
ラッパーを書くための専用の記法を知る必要があります（ユーザーのモチベーションをくじいてしまう）。
https://qiita.com/shunsukeaihara/items/7a31a3379936611cb9ee#cdef-struct%E3%81%97%E3%81%A1%E3%82%83%E3%81%86%E5%A0%B4%E5%90%88
なので、文字列をよしなに解釈するほうが楽だったりします。
もちろんユーザーにとって一番嬉しいのは言語ごとにラッパーがあることですが、とりあえずC APIを作るなら一旦文字列を返す方がユーザーにとって楽かなと思います。

あとそういえば、返したい中間パラメータはAudioQueryなのですが、これは内部で可変長の値を持つのでそもそもstructは無理かもです。
（structの中でvectorなどを使わずに可変長の値持つのってできましたっけ･･･？）

**Comment by Segu-g** [comment]
> もちろんユーザーにとって一番嬉しいのは言語ごとにラッパーがあることですが、とりあえずC APIを作るなら一旦文字列を返す方がユーザーにとって楽かなと思います。

ここで想定されているユーザーとはラッパー製作者の方でしょうか，それともライブラリの利用者の方でしょうか．
恐らく，言語にかなり熟達しないと一般の開発者はラッパーなしに動的ライブラリとの連携は難しいような気がします.
 一方,，ラッパー製作者はjsonエンコードされたデータ文字列を渡されるよりstructを渡してもらった方がインターフェースを構築するのは楽な筈です.
無論，stringをそのまま渡すだけのライブラリなら簡単に作れるかもしれませんがそのために利用者にjsonのパースを求めるのは天秤が釣り合っていないように感じます. 

> structの中でvectorなどを使わずに可変長の値持つのってできましたっけ･･･？

C言語で可変長の値を持つにはポインタの配列を用います.  reallocやfree等がデストラクタとして実装できないので面倒ですがC APIなら仕方ないところがあると思います.

**Comment by qwerty2501** [comment]
@Hiroshiba 
> Python用にCythonでCラッパーを書いて思ったのですが、structやvectorなどのCの独自言語仕様があるとコンパイルが面倒なんですよね･･･

これはOpaqueポインタで隠蔽すれば発生しない問題ですよね。

> あとそういえば、返したい中間パラメータはAudioQueryなのですが、これは内部で可変長の値を持つのでそもそもstructは無理かもです。

これもOpaqueポインタで隠蔽すれば内部での実装はC++を使えるため、structフィールドとしてvectorを使用可能です。代わりにアクセサ用の関数を結構生やしてあげる必要はありますが
mallocでもできますが、この文脈ではわざわざ危険を犯してまでvectorを使わずにmallocする必要はないと思います。

**Comment by Hiroshiba** [comment]
実際のユーザーの方（ライブラリの利用者）を想定していました！
たしかにラッパーがないと利用はかなり難しそうです。

ので、たしかに（ラッパー製作者も含めた）C++ユーザーから使いやすい形が良さそうに感じました！
structが良さそうです！

いろいろ議論していて、中間パラメータ（struct）周りは @qwerty2501 さんにおまかせできるとすごく嬉しいのかなと感じました！！！

- 単純なTTS（文字→音声）の実装
- AquesTalk記法の実装

の２つを @y-chan さんにお願いし、

- 中間表現（エンジンのQuery）のやりとりを実装

を @qwerty2501 さんにお願いできればおそらく最高かと思ったのですが、どうでしょう･･･？👀

**Comment by qwerty2501** [comment]
OKです。
私が担当するのは外部公開用の関数実装と、やりとりするための型定義でいいですかね？
Query機能の実装も必要ですか？

**Comment by Hiroshiba** [comment]
@y-chan  @qwerty2501  お二人ともありがとうございます！！

> 私が担当するのは外部公開用の関数実装と、やりとりするための型定義でいいですかね？
> Query機能の実装も必要ですか？

とりあえず外部公開用の関数実装と、やりとりの型定義をお願いしたいです！
（そこまでいけばみんなコミットできそうなので）

全Query機能の実装は大変な一方、openjtalkが無くても音声合成できるだけの情報・機能があると嬉しそう･･･？
ちょっとパラメータをリストアップしてみました。

<details>

```python
class Mora:
    text: str = Field(title="文字")
    consonant: Optional[str] = Field(title="子音の音素")
    consonant_length: Optional[float] = Field(title="子音の音長")
    vowel: str = Field(title="母音の音素")
    vowel_length: float = Field(title="母音の音長")
    pitch: float = Field(title="音高")

class AccentPhrase:
    moras: List[Mora] = Field(title="モーラのリスト")
    accent: int = Field(title="アクセント箇所")
    pause_mora: Optional[Mora] = Field(title="後ろに無音を付けるかどうか")
    is_interrogative: bool = Field(default=False, title="疑問系かどうか")

class AudioQuery:
    accent_phrases: List[AccentPhrase] = Field(title="アクセント句のリスト")
    prePhonemeLength: float = Field(title="音声の前の無音時間")
    postPhonemeLength: float = Field(title="音声の後の無音時間")
```

</details>

`is_interrogative`メンバーはありますが、擬似疑問文機能は初手で無くても良いかなと思っています。
（もちろん初手で実装してしまっても･･･！）

ちょっと量が多そうであれば、一旦pitch系とlength系は省いて、音素系とアクセントとpauseを実装とかもありかなと思いました！

**Comment by qwerty2501** [comment]
フィールド結構あるので、その分関数が多くなっちゃうんですが大丈夫ですかね？

**Comment by Hiroshiba** [comment]
関数というのは外に出すAPIでしょうか 👀
APIの数は３個くらい増えるかなと思っていて、それくらいなら全然大丈夫だと思います。
内部の関数がいっぱい増えるのは仕方ないと思います･･･！

**Comment by qwerty2501** [comment]
外に出すAPIですね。
structの実装を全て隠すので、アクセスさせたいフィールドがある場合はそのフィールドへのアクセサ関数を公開する必要があります。

例としては以下のような感じですね。関数名とかは結構適当です。
```c++
typedef struct VoicevoxMora_  VoicevoxMora;

char* voicevox_mora_get_text(VoicevoxMora* voicevox_mora);
void voicevox_mora_set_text(VoicevoxMora* voicevox_mora,char* text);
uint64_t voicevox_mora_get_pitch(VoicevoxMora* voicevox_mora);
void voicevox_mora_set_pitch(VoicevoxMora* voicevox_mora,uint64_t pitch);
...

```
こういう感じでユーザーにアクセスさせたいフィールド毎に関数を公開する必要があるので、フィールド数に比例して関数を公開する必要があり、結構な数になるかと

**Comment by Segu-g** [comment]
> フィールド結構あるので、その分関数が多くなっちゃうんですが大丈夫ですかね？
正直DLLでの互換性保ちつつ他のやり方知らないので代替案は出せませんが・・・


一応standard-layoutなクラスであればプロパティの対応するinitial sequenceは等しくなるはずなので，

+ プロパティの追加はクラスの末尾に追加する. 
+ 過去のABIに存在する関数でそれらのプロパティを使わない

もしくは

+ クラスのインスタンスを必ずライブラリ側で行い, ライブラリ利用者側にインスタンスを作成させない

という制約が入れば前方互換性は保てるとかがあります. 

https://timsong-cpp.github.io/cppwp/n3337/class.mem#19

参考: https://en.cppreference.com/w/cpp/language/data_members#Standard_layout



ただgetter/setterを用意するのとどっちが簡単かといわれるとgetter/setterの方が簡単で理解しやすいと思います.
 過去のABIに存在する関数でそれらのプロパティを使わないという制約は~~~ExみたいなAPIが生えてしまう温床にもなりそうですし，ライブラリ利用者側にインスタンスを作成させないという制約はそもそも禁止する方法がありません.
不透明型ではインスタンスの作成がライブラリ側のみで行えますが，インスタンスを作ることを縛れるのと縛れないのでは大きな違いですね・・・

**Comment by Segu-g** [comment]
そもそも互換性をどこまで保証すべきかという部分もあると思います. 先にも言ったようにQueryの中身を隠蔽すればABIは互換性を保ちますし, TTSでも頻繁に変更したい設定は別のバージョン互換性のある部分として別の構造体や引数に入れるのもありだと思います. 

動的ライブラリは差し替え可能なものですが同梱されることも多いものなので，個人的にはABIが変わったらバージョンも変えて良いんじゃないかなと思っていました.

**Comment by Hiroshiba** [comment]
> structの実装を全て隠すので、アクセスさせたいフィールドがある場合はそのフィールドへのアクセサ関数を公開する必要があります。

あー！　なるほどです。

互換性ですが、できれば維持できると嬉しいです！

ちょっとお二人の方法が完璧に理解できていないのですが、プロパティを注意深く足していく方法とアクセサを大量に用意する方法は、どちらかというと後者のほうが扱いやすいのかなと思いました！（OSSに向いてそう）
あまりにも関数が多くて使いづらいと感じた際は、ぜひ移行を考えたいです。

そういえば、パラメータは全てstructで持っておき、serializerとdeserializerを作って保存・読み出し関数を用意する手もあるのかなと思いました。
用意するのはこの３つくらいなので、APIの見た目的に綺麗なのが良さそうに感じたのですがどうでしょう･･･？👀

```c++
struct AudioQuery;
AudioQuery load_param();
void save_param(AudioQuery param)
```

**Comment by Hiroshiba** [comment]
そもそも互換性が必要なのは、パラメータを保存することを想定しているからだと思っていて、
であればその保存とロード時に互換性をもたせれば全部うまいこと行きそうだなと思いました。

Prosはsetter/getterを大量に用意しなくていい・互換性を気にしてstructの順番を決めなくて良い感じです。
Consは特に思いついてないです。

**Comment by Segu-g** [comment]
> そもそも互換性が必要なのは、パラメータを保存することを想定しているからだと思っていて

私はバイナリ互換性についての議論だと思っていました. 
参考までにABI (Application Binary Interface)互換性とは例えばライブラリAのバージョンがv1.0からv1.1に変わった時にv1.0を利用していたプログラムの変更や再コンパイルなしに共有ライブラリを差し替えるだけでそのまま動き続けることができる互換性を指します. 

@qwerty2501 さんの提案されているOpaque pointerは実際の構造体の中身を隠蔽し，Queryのインスタンスへの編集にはgetter/setter関数を提供することでtypescriptのInterfaceのようにユーザーにプロパティへの存在とそれらへのアクセス手段を全バージョンにて保証することができます. この際, 実際にOpaque pointerが保持しているstructがどのようなプロパティを持っているかはABIのバージョンが変わるたびに変化しますが, 不透明型なので生成, 管理は全てライブラリ側で行うこととなり, それをユーザーが気にすることはありません. ただしユーザーはqueryを構造体という形で見ることができず, 全てアクセサ経由で操作する必要があります. (もしくはそのバージョンの構造体への相互変換関数を毎バージョンに生やすとか?) 

私の提案したstandard-layoutという方法はC++においてC言語の構造体に変換可能なObjectが満たす POD (Plain Old Data) という構造がstandard-layoutかつtrivial typeであるという制約から, Query構造体を前のバージョンの継承関係となるように末尾にプロパティを実装するという試みです.  すなわちv1.0のQueryをQuery1, v1.1のQueryをQuery2とし, Query2はQuery1を継承するようになります. 
このとき, v1.0のfuncはQuery1*で呼び出すことができますが, Query2はQuery1を継承しているのでQuery2でも呼び出すことができます. 従ってこの方式で前方互換を確保するには

+ Queryのインスタンスを必ず最新のQuery2になるようにライブラリ側でのインスタンス化に制限する,
  + これは制限できない
+ 過去の関数での呼び出しをQuery1での呼び出しに制限する
  + Query2のプロパティを使うためには違う関数を生やす必要がありメジャーバージョンが変わる(互換性が打ち切られる)まで永遠に関数が増える. アクセサを提供するのとあまり変わらない. 

といった感じで@qwerty2501 さんの提案された方式よりかはかなりデメリットが目立つので自分でもあまりおススメしません. 

@Hiroshiba さんの提案されているserialize_param, deserialize_paramはQueryとしてJSONなどのDictionary Likeな中間表現を用いることでこれらの差異を吸収しようといった感じでしょうか? JSONなどの文字列型はCではパース, エラーハンドリング, 変更などが手間になりますがマイグレーションなどを気にしなければうまくいくかもしれません. 

どの方法を用いるにしてもQueryの内容を変更可能にしなければABI互換性を保つことができます. すなわち, TTSのパラメータについてだけQuery外に持っていきQuery自体は不透明型にすることで, 詳細なデータ構造は使いたいユーザーだけが解決してもらうという形もアリです. 無論Query外のパラメータを互換性を保ったまま変更は出来なくなるのでその辺りはしっかりと考える必要があります. また, Query内を変更したいというときは上記のいずれかの方法か，もしくはまだ知らない別の方法を用いる必要があるでしょう.

纏めると, Queryの編集をユーザーに提供する際に

+ @qwerty2501 さんの方法はQueryを不透明型にしたまま, アクセサを提供することでQueryを編集してもらう.
+ @Segu-g の方法はQueryを前のバージョンを継承するようにすることで関数の後方互換性を保ちながら，新しいプロパティを使用するには新しい関数を生やす.
+ @Hiroshiba さんの方法はQueryをJSON等の中間表現にすることで扱いにくいが必ず変換可能なqueryとして提供する

といった感じでしょうか

個人的には全アクセサをgetter/setterにするとstructが直観的に見れないので, そのバージョンの構造体への相互変換関数を毎バージョンに生やす形で@qwerty2501 さんの方法がいいのかなと思いました.

**Comment by qwerty2501** [comment]
@Hiroshiba おおむね @Segu-g さんが説明されてる通りABI互換性の話についての議論です。
ABI互換性についての議論のため、パラメータの保存有無にかかわらずこの問題は発生します。
ちょっと話が噛み合っていないようにも感じてますが、上手く伝わってますか？

**Comment by Hiroshiba** [comment]
すみません、よくわかりました！！僕が気にしていたのはデータの互換性の話でした。

ABI互換性についてしっかり知ってきました。
個人的には、最初はABIレベルの互換性がある状態で開発しない方が良いのかなと思いました。
理由は単純に、まだβ版で色々と実験しつつ進めるときに変更が大変そうなのと、そもそもABI互換性があると嬉しい人が現状ほぼいなさそうなためです。
一言でいうと、難しくて大変そうだけどユーザーがいなそうだなーと。。
実はそんなメンテナンス含めて開発は難しくなかったり、ラッパーの開発が楽になったりするのであれば最初から実装しても良さそうに感じました。

のちのちはABIを気にして作るのも良いのかなと感じました。
@Segu-g さんの仰っていたことに近いかもですが、ABI互換性を気にしないライブラリと、それをラップしてABI互換性を気にしたライブラリがあっても良いのかなと思いました。
多言語でVOICEVOXを使える薄いラッパーを開発する人はたぶんリビルドに抵抗がないので後者を使うし、直接C++アプリを作る人は前者を使いそうです。

（ただまあ、直接C++アプリを作る人よりラッパーを使う人のほうが多そうに感じているので、ラッパー作成に注力した方が喜ばれそうな気がしています）

**Comment by qwerty2501** [comment]
了解です。
となるとほぼstatic link libraryとほぼ同じ感覚で作れるはずなのでC API部分の実装は私じゃなくても大丈夫そうですね。(私担当のままでも大丈夫ですが)

> 直接C++アプリを作る人は前者を使いそうです。

C++で使う場合はソースコードごと一緒にコンパイルすると思うので特に気にしなくて大丈夫そうです。

ラッパーについてはたしかにそうですね。今どきC APIだけ提供してあっても誰も使わない可能性はありそうですしラッパー作成に注力したほうが良さそうです。というかC APIの提供いらないかもですね。
方針変えてまずはC APIを作らずに単純にC++のライブラリとして提供してある程度軌道に乗ったら各言語向けのラッパー作成にとりかかったほうがよいかもとちょっと思いました。

**Comment by qwerty2501** [comment]
> 別言語でラッパーを作るとき、C APIを動的ライブラリにビルドしたものをラップするのが楽なのかなと想像しています。

そうですね。ラッパーを手動で作成する場合はC APIが必要になってくると思います。
ただSWIGについて現状保留状態なのでもしSWIG使う場合になったらC++のclassを対象として出力できそうなのでその場合はC APIを作る必要がない可能性が出てきます。i OS向けには手動で作る必要がありそうですが。
またC APIが必要になったとしても後から作るということはできますし、第一段階としてはなしでもいいかなとちょっと感じたといったところですね。


またC APIについてですが、structの実装を公開しても文字列や配列についてはheapを確保してるのでこれらを開放する必要があります。開放用の関数を定義してもユーザーが気付けるかどうかはちょっと怪しいかもしれません。この場合ドキュメントなどで周知するぐらいしかなさそうですが・・・

**Comment by shigobu** [comment]
C#使いとしては、C APIをラップする方が簡単です。

**Comment by Hiroshiba** [comment]
YMM4にCoeFontが初期搭載されるニュースが発表されました。
VOICEVOXが最初に到達できる未来だったかもしれず、正直とても悔しいです。
（思いつけず、不甲斐なくて本当に申し訳ないです･･･。）

VOICEVOXも同じこと（TTSシステムの同梱）が可能になる状態を、なるべく早く実現したいなと感じました。
そのための手がこのC++ライブラリ作成プロジェクトだと思います。

身勝手なのですが、ロードマップ（というか優先順位）を引き直せればと思います🙇
「Windows上でインストールすることなくVOICEVOXのTTSが可能」という状態を最速で目指すロードマップです。

高優先度

- [ ] とりあえず動くTTS関数（テキストを入力したら音声が出てくる）をマージする
  - とりあえずOSは何でもOK
- [ ] Windowsで動くようにする
- [ ] Windowsでの使い方例を書く
  - とりあえず言語はC++
- [ ] とりあえずリリースする
  - このzipファイルを展開してこのコードを書けば動く、という状態を目指す

オプション

- [ ] AquesTalk記法に対応する
- [ ] VOICEVOX Coreの軽量エディションを作る（ @hiroshiba )
- [ ] https://github.com/VOICEVOX/voicevox_core/issues/86

僕たちの今の立ち位置から、僕たちのスキルを合わせれば、おそらく２週間でリリースまで到達できると思います。
その立ち位置にいるのは間違いなくみんな（特に @y-chan さん）のおかげです。

コア開発に携わってくださったVOICEVOXチームの優秀なメンバー（敬称略   @Yosshi999 @Oyaki122 @y-chan @aoirint @PickledChair @qwerty2501 @Segu-g @shigobu ）の皆様、もしよければお力をお借りしたいです。
どうか、どうかよろしくおねがいします･･････！！🙇

**Comment by Hiroshiba** [comment]
（Discordに書きたかったのですが今不調っぽいのでこちらで。。）
初手はおそらく @y-chan さんの、TTSを可能にするプルリクエストが最速かなと感じています。
マージしてしまえばあとはパラレルで動けるので、なるべく早くマージできるとすごく嬉しいです（急かしてしまって申し訳ないです。。）
お手数おかけしてしまうのですが、もしよければ何卒よろしくお願いいたします🙇

**Comment by Hiroshiba** [comment]
すごく昔に作ったLite版モデルで音声合成してみました。

通常版
https://user-images.githubusercontent.com/4987327/157507761-2331809e-c446-4527-9f60-16f6f308d9df.mp4

https://user-images.githubusercontent.com/4987327/157507771-747eb47c-d66f-4632-bba3-8038fedb5a86.mp4

**Comment by qwerty2501** [comment]
あまり状況を把握していないのですが、YMMってすでにvoicevox APIに対応してませんでしたっけ。
今あるengineを同梱する方向だとよくないんでしょうか

**Comment by Hiroshiba** [comment]
ファイル容量がざっと300MBくらい違ったりします。
仮にVOICEVOXの軽量版ができれば（辞書を抜けば）50MBくらいになるので結構差がありそうです。
サーバーを起動するexeとdllだと取り回しやすさがだいぶ違うと思うので、なんにせよ早めに作りたいところです。

**Comment by Hiroshiba** [comment]
@qwerty2501 
あ、issueの内容とちょっと異なるフランクな話題はVOICEVOXのユーザーコミュニティdiscordサーバーを間借りして話していたりします。
かなり気軽にいろんな話ができるので、よかったらぜひ！
https://twitter.com/hk_coil424/status/1432351677026160641

**Comment by Hiroshiba** [comment]
@y-chan さんのとりあえずTTSできるコードがマージされました！
（本当にありがとうございます！！！）
https://github.com/VOICEVOX/voicevox_core/tree/cpp-library

どんどん機能実装＆使い勝手を良くしていきたいので、もしよければプルリクエストお待ちしています！
（ブランチがmainではないのでご注意ください）

**Comment by Hiroshiba** [comment]
オプション側のコード追加もじゃんじゃんやっていけると嬉しいですね･･･！

**Comment by Hiroshiba** [comment]
製品版をビルドしてみました。TTSが動きました！

- https://github.com/VOICEVOX/voicevox_core/issues/97

残りやりたいことはまだまだありますが、一段落だと思います。
C++のサンプルコード（example/cpp）実装や、テストの実装などが次の課題だと思います。
じゃんじゃん進めていけるととても嬉しいです。
https://github.com/VOICEVOX/voicevox_project/issues/1#issuecomment-1062100395

**Comment by Hiroshiba** [comment]
こちら、別言語で気軽に使えるようにしたり、いろんなサービスで気軽に利用できるようにしたりできると世界が変わってくると思うので、どんどん進めて行きたいかもです。

[ここのリスト](https://github.com/VOICEVOX/voicevox_project/issues/1#issuecomment-1062100395)のタスクを整理すると、これらがメインで残っていそうでした。

- Windowsで動くC++用のサンプルコードを書く（example/cpp？）
- ↑のドキュメントを書く
- とりあえずプレリリースする

オプションとしてはこれらがありそうです。

- VOICEVOX Coreの軽量エディションを作る（ @Hiroshiba )
- Mac・Linuxでも動くようにする
- https://github.com/VOICEVOX/voicevox_core/issues/86
- コピペすればOKなライセンス情報テキストも用意
- TTSのテストを書く
- AquesTalk記法のテストを書く
- 本リリースする

もしよかったらぜひ･･･！

**Comment by shigobu** [comment]
Windowsで動くC++用のサンプルコード、Visual Studio(VSCodeで無い)のプロジェクトで良いなら、私作ります。

**Comment by Hiroshiba** [comment]
おお！ぜひお願いします！！

**Comment by Hiroshiba** [comment]
@shigobu さん、Windows用のサンプルありがとうございます！！
@Oyaki122 さんも、埋め込みありがとうございます！！

もう動的TTSライブラリのリリースができる気がします！
ただテストコードがまだだったり、linux用のサンプルコードがなかったりなのが少し不安ポイントでもあります。
引き続き、このあたりの実装を募集しています。

* Mac・Linuxでも動くようにする
* TTSのテストを書く
* AquesTalk記法のテストを書く

よかったらぜひ！！

**Comment by PickledChair** [comment]
> - Mac・Linuxでも動くようにする

今日 Mac・Linux 向けの小さなサンプルコードを書いてみていました（コマンドの引数で与えられたセリフから音声を生成し、`audio.wav` を生成する単純なものです）。問題なく動くようです。あとは CMake でビルドできるようにしたいと思って作業しています。

**Comment by Hiroshiba** [comment]
おー！！ありがとうございます！！お待ちしております･･･！

**Comment by Hiroshiba** [comment]
@PickledChair さん、ありがとうございます！！！
次のリリースで音声合成ライブラリができたことを胸を張ってリリースできそうです！！

もしC++でのテストに興味があるorできる方がいらっしゃったら、こちらをお願いできると将来的にリファクタリングしやすかったりで安心かもしれません。

* TTSのテストを書く
* AquesTalk記法のテストを書く

Google Testというのが良さそうに感じています。
https://rinatz.github.io/cpp-book/test-how-to-gtest/

**Comment by qwerty2501** [comment]
ちょうどユニットテストフレームワーク導入PR作ろうと思って調べてたんですが、Catch2もありかなとは感じました。
data driven testをやろうとすると書きやすさではこっちに軍配があがりそうかなと

**Comment by Hiroshiba** [comment]
おお！！！　PR、お待ちしています！！

Catch2、たしかにdata driven testをしやすそうに見えました。

日本語資料の有無でいうと、google testは調べると（なぜか）OpenCVが語ってくれていて頼りになりそうでした。
Catch2は英語のドキュメントとにらめっこすることになりそうですが、総合的にはこちらのほうが便利そうに感じました。

（google testとcatch2どっちも調べてたんですが、どちらもマクロまみれでテストがめちゃくちゃ書きづらそうだなと感じました･･･････。これVSCodeで補完とか効くんですかね。。。
fixtureもclass定義で実現できるけど、C++のclass定義のややこしさがそのままテストの読みづらさになるので、メンテ大変になりそうだなと直感しました。。。）

**Comment by qwerty2501** [comment]
あほんとですね。OpenCVに何故か日本語ドキュメントがある。ただ公式ではない以上ドキュメントがいつまでメンテされるかわからないのであまり当てにはしないほうがよいかなとは思いました。すでに古い可能性もありますし。
> google testとcatch2どっちも調べてたんですが、どちらもマクロまみれでテストがめちゃくちゃ書きづらそうだなと感じました･･･････。これVSCodeで補完とか効くんですかね。。。

その２つ以外も含め主要なC++のUnit test frameworkは軒並みマクロに依存しまくってます。まあそういうものだと思って諦めてください。
VSCodeで補完効くかどうかは私はVSCode使ってないのでよくわからないですね。

google testの利点を上げるとすれば、メンテが打ち切られる可能性が限りなく0に近いことでしょうか。ただところどころレガシーな部分は目立つのでそのあたりを天秤にかけてどうかといったところですかね。

**Comment by Hiroshiba** [comment]
こちらでC APIの改善に関して議論されています。

- https://github.com/VOICEVOX/voicevox_core/pull/217

**Comment by Hiroshiba** [comment]
こちら、コアの言語がC++ではなくRustに変わったため、タイトルを変更いたしました。
･･･今思ったけど、もう完了としてしまっても良いかもしれませんね･･･。あとはTTS周りのテストくらい･･･？

**Comment by y-chan** [comment]
こちらですが、一旦closeしてしまって、個別にIssueを立てる方針にしたいと思います。
理由としては、ほぼ全てのタスクが完了し、Rust化の恩恵でテストまで実装できているからです。(e2eテストは実装できてないけど、unitテストでも十分な気がする...?)
VOICEVOX Coreを一般的に配布できる形にはなってきていますが、Coreは現在新APIやクラス設計 (voicevox/voicevox_core#280 voicevox/voicevox_core#370)が進んでおり、多分それが完了するまでプレリリース・リリースはしないので、一旦無視して良いかなと思いました。
あと残っているタスクは辞書APIの同梱(voicevox/voicevox_core#265)が挙げられますが、まあ個別にIssueが展開されているので、このプロジェクトは完了としていいかなと思いました！

というわけで、一旦おつかれさまでした！！！
