### ISSUE TITLE
コアのonnx化

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_project#4]
今（0.9.3）コアはlibtorch製になっています。
onnx製にすると、スピードが上がり、容量が劇的に軽くなることがわかりました。
これは、onnxに移行するプロジェクトです。

onnx化自体はほぼ完了しています。

- https://github.com/VOICEVOX/voicevox_core/pull/21

ただ、もともとコアはOSSとして作られておらず（暗号化する関係で）、必要な機能をOSSとして再実装していく必要があり、それらのタスクの量が多めになっています。

- https://github.com/VOICEVOX/voicevox_core/issues/27
- https://github.com/VOICEVOX/voicevox_core/issues/29
- https://github.com/VOICEVOX/voicevox_core/issues/30
- https://github.com/VOICEVOX/voicevox_core/issues/31

**Comment by Hiroshiba** [comment]
onnx化に関して、バージョン0.10で取り込めると最高だなと考えています。
取り込むためのタスクを的確に遂行できるのは @Yosshi999 さんが最適かなと個人的に感じているのですが、お任せすることはできますか･･･？

具体的には　↑　にあるタスクをやっていくことになるかなと思っています。
僕も手伝いたいので、各issueをアサインしつつ順次やっていければ良いかなと思うのですが、いかがでしょうか。

**Comment by Yosshi999** [comment]
👍

**Comment by Hiroshiba** [comment]
ではアサインさせていただきます！！

**Comment by Hiroshiba** [comment]
onnx化プロジェクトの成果が含まれたバージョン0.10.4がリリースされました！！
https://twitter.com/voicevox_pj/status/1489602429473951744

onnx化に関しては、onnx化するさいにモデルの出力が若干変わってしまうという課題がまだ残っています。

- https://github.com/VOICEVOX/voicevox_core/issues/73

onnx化するという目的は達成できたと思うので、このプロジェクトをcloseしたいと思います。

無事リリースすることができました！！！
@Yosshi999 さんを筆頭に関わってくださった皆様、本当にありがとうございました！！！

ちなみにですが、onnx化ができたので、web版VOICEVOXとか、スマホ版VOICEVOXとか、新たなプロジェクトも立ち上げたいなと思ってます。
もしご興味あれば、ぜひ・・・！
