### ISSUE TITLE
エディタ：GitHub Pages上でPRプレビューを実装する

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/voicevox_project#58]
2024/11/16：実装しました 🎉 

- 表示側リポ：https://github.com/VOICEVOX/preview-pages
- 表示ページ：https://voicevox.github.io/preview-pages/
- 更新のWorkflow：https://github.com/VOICEVOX/voicevox/actions/workflows/DANGEROUS_trigger_preview_pages.yml

----

## 内容

エディタでPRを出すとPRの内容（Storybookやブラウザ版）が表示されるやつを実装したいです。

### Pros 良くなる点

レビューがしやすくなる

### Cons 悪くなる点

複雑になりそう

### 実現方法

https://github.com/sevenc-nanashi/vv-preview-demo-page
https://github.com/sevenc-nanashi/vv-preview-demo-bot
やってみました。
- page：
  - pull_requestでartifactをビルドする
  - pull_request_targetでdemo-botを発火させる
- bot：
  - workflow_dispatchでプルリク一覧とビルド済みのArtifactを収集してPagesにあげる

みたいな感じです。

## その他

（なし）

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！
メンテナ視点からちょっと補足説明させていただきます 🙏 　（メモと、他の方への共有を兼ねて。）

### 目的

プルリクごとにブラウザ版エディタやStoryook等の専用静的ページを作り、レビューをしやすくして開発効率を高めるのが主目的です。
（あと楽しそう。）

### 手段

パッと思いつく方法はNetlify等ですが、こちらは価格的にスケールが難しそうだと判断しました。
OSSとして誰でも編集可能にするにはチームでの開発になりますが、１人月３０００円で大変です。
あと誰でも参加できないので、折衷案としてGithub Pagesで開発する方針となっています。
（試してくださった @sevenc-nanashi さんに感謝です！！！）

### 展望

汎用的な形にできれば、VOICEVOXエディタ以外でもとても有用なフレームワークになるのではと個人的に期待しています。

**Comment by Hiroshiba** [comment]
@sevenc-nanashi 少し見させていただきました！
仕様として気になる点をいくつか･･･！

1. `-page`と`-bot`はどっちがVOICEVOX/voicevox想定で、どっちがどのリポジトリを想定してますか 👀 
	* たぶんpageがVOICEVOX/voicevox、botがgithub pagesをデプロイする先？
2. page側で、`build_page.yml`と`trigger_bot.yml`が同時実行される、つまりpushされたものがビルドされ終わる前にbotが走り始めそう？
3. これプルリク時にbot側からpageのartifact見れるのかな
	* 試してないんでしたっけ。PR作ってみます！

**Comment by sevenc-nanashi** [comment]
> 1. `-page`と`-bot`はどっちがVOICEVOX/voicevox想定で、どっちがどのリポジトリを想定してますか 👀 

-pageがvoicevox/voicevox、-botがvoicevox/editor-preview（仮称）ですね。


> 2. page側で、`build_page.yml`と`trigger_bot.yml`が同時実行される、つまりpushされたものがビルドされ終わる前にbotが走り始めそう？

はい。そういう前提でコードを書いています（Artifactができるのを待機）

> 3. これプルリク時にbot側からpageのartifact見れるのかな

というと？GitHub APIではアクセスできますね。

**Comment by Hiroshiba** [comment]
> > 3. これプルリク時にbot側からpageのartifact見れるのかな
> 
> というと？GitHub APIではアクセスできますね。

（もう直ってそうですがメモとして）
`on: push`だったので、fork先リポジトリにはartifactができるけどfork元リポジトリにはできないはずで、だとすると権限がないだろうな〜と思った次第でした！

**Comment by Hiroshiba** [comment]
> > 2. page側で、`build_page.yml`と`trigger_bot.yml`が同時実行される、つまりpushされたものがビルドされ終わる前にbotが走り始めそう？
> 
> はい。そういう前提でコードを書いています（Artifactができるのを待機）

おーなるほどです！
artifactが正常に作られなかった場合とかも大丈夫そうでしょうか。
デプロイ用のコンテナが起動しっぱなしになっちゃうので。

まあでもそこ含めてコード読むとわかりそう！！

**Comment by Hiroshiba** [comment]
チェックしたい項目メモ

- [ ] PRがcloseするとページが消えるか
- [ ] actionsとして切り出しが可能か（マストではない、だいぶ複雑になりそうならactionsにするのもありかもくらいの気持ち）

**Comment by sevenc-nanashi** [comment]
> artifactが正常に作られなかった場合とかも大丈夫そうでしょうか。
デプロイ用のコンテナが起動しっぱなしになっちゃうので。

Jobが失敗落ちしたらArtifactを取らないようにしています。

これ、初回コントリビュータの承認待機がしんどいですね…

**Comment by Hiroshiba** [comment]
ちょっと提案です！！　まだ考えきれてないので穴あるかもですが！

PRごとにartifactを持ってこようとするpull型ではなく、push型にするのはどうでしょう？ 👀 

今のロジックはこうだと想像してます：

* ページを作りたいリポジトリA（`-page`）
* ページを配置したいリポジトリB（`-bot`）

1. AにPRがpushされる
2. Aでページをビルドし、Aにartifactを配置する
3. ↑と同時に、AがBのartifact収集workflowを回す
4. Bは2が終わるかエラーになるまで待機
5. Bのgithub pagesにpush
6. AのPRがcloseされる
7. AがBのworkflowを回す
8. Bがgithub pagesから削除（未確認）

これをpush型にするとこうなりそう：

1. AにPRがpushされる
2. Aでページをビルドし、Aにartifactを配置する
3. ↑の**完了後**、AがBの**artifact回収workflow**を回す
    * リポジトリ名・PR番号・artifactのid？（・デプロイ先のサブディレクトリ）を引数で渡す
4. Bのgithub pagesにpush
5. AのPRがcloseされる
6. AがBのworkflowを回す
    * リポジトリ名・PR番号を引数で渡す
7. Bがgithub pagesから削除（未確認）

push型の利点はビルドが終わった後にデプロイを開始できる点だと思います。
あとworkflow_dispatchで作成や削除を自由に実行できたり、他のリポジトリを追加する時にコード変更が不要だったり、パラレルに複数動かせたり、デプロイコードを不要にできるかもです。

欠点は作成・削除用２つのworkflowが必要なこと、`on: pull_request`から`on: pull_request_target`を呼べるか不明なこと（できるんだろうか。。。）とか･･･？

そもそも超荒業として、リポジトリAからリポジトリBへ直接git pushしちゃう手もあるかもです。
これだと多分Bからworkflowをなくせるかも･･･？？

ちょっと色々精査してないので粗いかもですが、一旦アイデアまで！！

**Comment by Hiroshiba** [comment]
↑で提案したpush型の方法ですが、おそらくPRを出した側でビルドした後、fork元（target）側でワークフローを発火させる必要があるのですが、その手法がGithub側に用意されてなさそうでした 😇 
なのでpull型で作るしかなさそう！！

**Comment by sevenc-nanashi** [comment]
> `on: pull_request`から`on: pull_request_target`を呼べるか不明なこと（できるんだろうか。。。）とか･･･？

無理だと思います...
基本的にWriteアクセスはやすやすと与えられないような設計を感じるので、それをGitHub公式が実装するのはかなり考えづらいです。

**Comment by Hiroshiba** [comment]
ですよね。。 😇 
よし、 @sevenc-nanashi さんの実装を基軸に進めて行けると良さそう！！！

ちょっと設計を議論したく、いくつか質問させてください！

1. actionsに切り出しはできそう？
	* いろんな人が使えたり、 @sevenc-nanashi さん自身別のとこでもサクッと使えると便利そうだと思ったので
	* 別にマストではないはず
2. 1が行ける場合、actionは１つにできそう？
	* 今page→botに通知するworkflowと、bot側のworkflowの２つがあるはず
	* これをひとまとめにできそうか
3. 2が行ける場合、page側にactionを導入するだけにできそう？
	* これができれば、「push用のリポジトリを作って、PR用ページを作りたいリポジトリ側だけの変更すれば完了」になるので相当使いやすい
	* でも権限周りが難しそうな予感

**Comment by sevenc-nanashi** [comment]
> actionsに切り出しはできそう？ 

ちょっとやっていましたが、かなり面倒（例えばブランチのフィルタのパーサーを作るとか...）なのでパスしたいです...

**Comment by Hiroshiba** [comment]
なるほどです！！！
（何でフィルターがいるんだろ、元リポジトリの`release-*`と`main`以外のプレビューページを作らないためとか･･･？）

１点気になったのですが、artifactの期限が切れるとページが作られない感じでしょうか 👀 
最大期限は90日にできるので期限切れでページが表示されないのは良さそう。エラーになると困りそう！

アーキテクチャの更新とかってまだ思いついたりされますか 👀 
もし一旦これが最高そうであれば、この形で進められればと思ってます！！
今考えてるのは、previewページリリース用のリポジトリの設定権限を @sevenc-nanashi さんにも付与し、メンテナンスをほぼ完全にお任せするとかだとやりやすいのかな～とか思ってたりします！

**Comment by sevenc-nanashi** [comment]
> （ちなみに何でフィルターがいるんでしょう 👀 　元リポジトリのrelease-*とmain以外のプレビューページを作らないためとか･･･？）

元だと、project-*とmainとプルリクのプレビューを作るようになってましたが、例えば：
- project/*にしたかったり
- プルリクは省きたかったり
- 最新5件だけにしたかったり

とか色々とカスタマイズしたいと思うんですよね。それをactionsの引数で実装するのが面倒だなぁ…と。

> １点気になったのですが、artifactの期限が切れるとページが作られない感じでしょうか 👀

多分作られなくなりますね。でもエラーで全体が死ぬことはないはず。

**Comment by Hiroshiba** [comment]
なるほどです！！
フィルタは正規表現にする形にしておけば実装もそんなに難しくないかもとかちょっと思いました。
でもActions実装はマストじゃないと思います！

[このコメント](https://github.com/VOICEVOX/voicevox_project/issues/58#issuecomment-2455233052)の後半のこちらはどうでしょう 👀 

> アーキテクチャの更新とかってまだ思いついたりされますか 👀 
> もし一旦これが最高そうであれば、この形で進められればと思ってます！！
> 
> 進め方として今考えてるのは、previewページリリース用のリポジトリの設定権限を @sevenc-nanashi さんにも付与し、メンテナンスをほぼ完全にお任せするとかだとやりやすいのかな～とか思ってたりします！
> 多分トークンとか色々設定が必要そうだな～と。
> 
> フレームワークやライブラリの選定も自由で･･･！
> 一応癖のないライブラリや大体の効くものであれば、いざという時にメンテナンスできるのでありがたくあります 🙏 
> ちなみに、硬いコードを書くときの[ライブラリの選定基準のガイドライン](https://github.com/VOICEVOX/voicevox_project/blob/009dd4bafb3eedbbf7df653d25937e8b9fdbe165/docs/%E5%88%A4%E6%96%AD%E7%AD%89%E3%83%A1%E3%83%A2.md#%E4%BE%9D%E5%AD%98%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E9%81%B8%E5%AE%9A%E5%9F%BA%E6%BA%96)があるのでもしご興味あれば！

**Comment by sevenc-nanashi** [comment]
> とりあえず進めてみる

現在進行形で進めてますね。
とりあえずeditor-previewって名前にしようと思っています。

（あと何故か自分にリポ作成権限がありました）

**Comment by Hiroshiba** [comment]
なるほどです！！楽しみ！！

名称についてですが、ちょっと将来的にいろんなリポジトリのプレビューを担えないかと思ってたりします…！
１箇所にしたい理由はartifact収集コードの管理が楽なためです。

なので一旦editor専用じゃない名前だとありがたいかもです！！
preview-pagesとか…？

リポジトリは作っちゃっていただいてもOKです！
権限周りやリポジトリ保護等はこちらで設定します🙏

他のリポジトリと揃えて、mainブランチへの直接のコミットはせず、プルリクベースで進める感じで良いでしょうか？
あるいは最初動くまではmainに直接pushでも良いかも。そして完成したら履歴全部消してinitial commitをforce pushしてそこからPRベースにするとかでも…！！

なるべくやりやすい形で進められれば🙏

**Comment by sevenc-nanashi** [comment]
自分のフォークで動くまでやった後にPull RequestのSquash MergeをInitial Commitみたいにする、でやろうと思います。

**Comment by Hiroshiba** [comment]
導入のためにやること・やったことのメモを残していこうと思います 🙏 

まずはGithub App作成します！

**Comment by Hiroshiba** [comment]
Github Appを作り、VOICEVOX Orgにインストールしました。
VOICEVOX/voicevoxにのみ許可を与えてます。

**Comment by Hiroshiba** [comment]
`preview-pages`内にsecretsも４つとも作成しました。
既存のものはわかりやすいように削除しました。
これで`preview-pages`側はOKなはず！

**Comment by Hiroshiba** [comment]
VOICEVOX/voicevox側の作業に入りました。

`TRIGGER_PREVIEW_PAGES_TOKEN`を設定します。（この説明が`preview-pages`側にあったほうが良いかも）
`preview-pages`への`Workflows`のR&Wを許可したトークンをVOICEVOX/voicevoxにセットしました。

[`preview-pages`側のワークフロー](https://github.com/VOICEVOX/preview-pages/actions/runs/11698612576/job/32579179120)が落ちてますが、とりあえず準備できたのでVOICEVOX/voicevox側のPRをマージします！

**Comment by Hiroshiba** [comment]
pages周りで落ちてそう。そういえば許可与えないといけなそう、Settingsを見直します。
![Uploading image.png…]()

**Comment by sevenc-nanashi** [comment]
voicevox/preview-pages：
Pagesのビルドのオプションを間違えていたので修正（ブランチからデプロイ -> Actionsからデプロイ）

**Comment by Hiroshiba** [comment]
VOICEVOX/voicevox側のtriggerが落ちてそう。なんでだろ、調べます！
workflowのR&Wだけじゃダメだったりするのかな。
https://github.com/VOICEVOX/voicevox/actions/runs/11698731079/job/32579503800

**Comment by Hiroshiba** [comment]
うーーーーーーん　PATの設定は雰囲気合ってる気がする
<img width="409" alt="image" src="https://github.com/user-attachments/assets/3d3d7213-91c1-495d-8de4-e67064f4df5d">

それをちゃんとVOICEVOX/voicevoxに設定できていそうではある
<img width="995" alt="image" src="https://github.com/user-attachments/assets/122c9adb-ce8a-4e11-b2e0-ffa97d134763">

コピペミスった可能性あるかな･･･。再設定してみます。

**Comment by Hiroshiba** [comment]
うーーーーん詰んだ！！！
Organizationだとworkflow dispatchに制限があるとか･･･････？

**Comment by Hiroshiba** [comment]
`voicevox/preview-pages`ってなってるけど、`VOICEVOX/preview-pages`じゃないとダメだったりする･･･？

あとは`update_pages.yml`側が
```
permissions:
  contents: read
  pages: write
  id-token: write
```
になってるけど、このパーミッションが`TRIGGER_PREVIEW_PAGES_TOKEN`側に必要とか･･･？

**Comment by Hiroshiba** [comment]
お、まわりました！

`Actions`への権限が必要だったっぽいです。たぶんwrite権限。
確かに説明はこうなってるので、合ってそう。

> Actions 
Workflows, workflow runs and artifacts.

ちなみに`Workflows`の説明

> Workflows 
Update GitHub Action workflow files.

**Comment by Hiroshiba** [comment]
mainブランチのbuildは成功してそうですが
https://github.com/VOICEVOX/voicevox/actions/runs/11698731082

収集に失敗してそう･･･？
https://github.com/VOICEVOX/preview-pages/actions/runs/11699103159/job/32580492466
> 2024-11-06 07:33:03.281 +00 info app·Branch main: No build check found

**Comment by Hiroshiba** [comment]
artifactにアクセスするにはまた別の権限が必要だったりとか･･･？

**Comment by Hiroshiba** [comment]
うーーーんどこが原因だぁ
https://github.com/VOICEVOX/preview-pages/actions/runs/11699304255/job/32581048596

ちょっとartifactのread権限付けてみます。
（たしか非ログインだとartifactダウンロードできないので気になってる）

**Comment by Hiroshiba** [comment]
artifactsは`Actions`権限っぽいので付けてみました

<img width="543" alt="image" src="https://github.com/user-attachments/assets/c22a5579-c8da-45e0-99ac-c8c6619daa0f">


https://github.com/VOICEVOX/preview-pages/actions/runs/11699304255/job/32581144789
> 2024-11-06 07:52:43.345 +00 info app·Branch main: No build check found

うーーーーむダメそう。

**Comment by sevenc-nanashi** [comment]
どうやらWorkflowの名前じゃ無くJobの名前（i.e.：`jobs: `下のキー）だったようです...

https://github.com/VOICEVOX/voicevox/pull/2343

**Comment by Hiroshiba** [comment]
おー通知まで進みましたね！！！
通知されるリンクが違うかもですが･･･！！

**Comment by sevenc-nanashi** [comment]
プレビューとか色々を直しました：https://github.com/VOICEVOX/preview-pages/pull/5

**Comment by Hiroshiba** [comment]
リスト一覧が表示できてないかも･･･！

https://voicevox.github.io/preview-pages/

`https://voicevox.github.io/preview-pagespreview/downloads.json 404 (Not Found)`
というエラーが。

**Comment by Hiroshiba** [comment]
動いたー！！！！！！　良い感じ！！！

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/a8559321-8a7a-4f47-aea6-7594346a6ea7">

**Comment by Hiroshiba** [comment]
@sevenc-nanashi 
プレビューページ、安定稼働してそうですね！！！

ということでタスクは完了かなと思いました、お疲れ様でした！！実装ありがとうございました！！！

今回も良い機能が実装できたということで、こんな感じで SNS にツイートしたいと思っています！
何かコメントあればぜひぜひ 🙏 
```
#VOICEVOX開発状況 
プルリクエストごとにプレビューページが作られるようになり、その時点でのエディタやStorybookがブラウザで確認できるようになりました🎉（ソフトウェアの見た目には影響ありませんが、開発が楽しくなりました。）
【開発者:@sevenc_nanashi】
https://github.com/VOICEVOX/preview-pages
```

あ、あとこのissueは数年間の間に何度も参照すると思います！
なのでポータル的にいろんな URL をdescription内に貼っていただけると助かります 🙏 

と言っても[リポジトリ](https://github.com/VOICEVOX/preview-pages)と[プレビューURL](https://voicevox.github.io/preview-pages/)と、あとはVOICEVOX/voiecvoxのtrigger workflowくらい･･･？

その変更と、このissueのクローズをもってプロジェクトの完了とさせていただければと！！
再度、ありがとうございました！！

**Comment by sevenc-nanashi** [comment]
一番上に書き出したのでCloseします。おつ！

**Comment by Hiroshiba** [comment]
ツイートさせていただきました！！ https://x.com/voicevox_pj/status/1857625465680441836
