### ISSUE TITLE
ユーザー辞書機能を作る

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_project#6]
エゴサをしている感じ、VOICEVOXが使いづらいと言われるうち調整が難しいことの次くらいに多く言われているのが、辞書機能が無いことです。
専門用語や人名は毎回アクセント位置を調整したりする必要があり、たしかに手間が大きいと思います。

このプロジェクトでは上述の課題を解決するために、ユーザー辞書を導入します。

openjtalkにその機能があるので流用する形になりますが、エンジン側でエンドポイントを実装したり、辞書をコンパイルしたり、エディタ側にUIを作ったりとかなり大きな工事が必要です。

もうすでにいくつかissueが作られているのでまとめます。

- https://github.com/VOICEVOX/voicevox/issues/175
- https://github.com/VOICEVOX/voicevox_engine/issues/284

ちょっと工程がどんな感じになるか考えてみました。
これ１つ１つに対しPRがあるという粒度です。

### エンジン

- must
  - [x] 単語登録＆辞書に追加＆コンパイル
    - 名詞のみで、発音・表層系・アクセント型のみ 
  - [x] 単語の一覧を返す
  - [x] 単語の上書き＆消去
- want
  - [x] 品詞ごとのコストのパーセンタイル値作成コード＆パーセンタイル値データ追加
  - [x] 名詞でのコストのパーセンタイル値を追加
  - [x] 名詞以外のわかりやすい品詞を追加（動詞・形容詞とか。可能なら語尾も） VOICEVOX/voicevox_engine#355
  - [x] 辞書のexport/import
- can
  - [ ] アクセント結合規則・読みの追加
  - [ ] 検証に必要な情報の作成コードを追加
  - [ ] 名詞以外の品詞を追加

### エディタ

- [x] 名詞の単語登録（アクセント位置は数値入力）
- [x] 名詞の修正・消去
- [x] アクセント位置をリッチなUIで入力
- [ ] 品詞を選べる VOICEVOX/voicevox#916

**Comment by Hiroshiba** [comment]
すでにエンジン側の実装の大半をやってくださっている @takana-v さんをアサインさせて頂きます。
なかなか大掛かりで時間がかかるかもですが、多くのユーザーが待望する機能だと思います。
頑張りましょう････････！！！

**Comment by Hiroshiba** [comment]
@takana-v さん

mustの機能がエンジンに全部実装され、 @y-chan さんの貢献もあって無事UIをリリースできるようになりました！！
もしよかったらツイートする際に @takana-v さんに言及させていただきたいのですが、よろしいでしょうか👀
もしOKでしたらツイッターIDを教えて頂けると･･･！

**Comment by takana-v** [comment]
はい、大丈夫です。
ツイッターのIDは@taka7nです。

**Comment by y-chan** [comment]
こちら、ほぼ完了しているので、closeしたいと思います！
canの部分はあまり重要では無いので、必要になった時にIssue化する形で良いかなと...!

おおむね完了してからそこそこ時間が経ちましたが、改めておつかれさまでした...!
